/// Flutter icons Account
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Account
///      fonts:
///       - asset: fonts/Account.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Account {
  Account._();

  static const _kFontFam = 'Account';
  static const _kFontPkg = null;

  static const IconData account_3 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_6 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_5 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_4 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
